# Generated by Django 5.0.6 on 2024-07-05 09:11

import big_three_test.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to=big_three_test.utils.generate_upload_path, verbose_name='Файл')),
                ('file_type', models.CharField(max_length=50, verbose_name='Тип файла')),
                ('size', models.CharField(max_length=50, verbose_name='Размер файла')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-created'],
            },
        ),
    ]
